version: "3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - 9443:9443
    volumes:
      - ${ROOT}/data:/data
      - /var/run/docker.sock:/var/run/docker.sock